export const CREATE_USER_SESSION = "CREATE_USER_SESSION";
export const LOGIN_USER = "LOGIN_USER";
export const ERROR_USER = "ERROR_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const types = {
    CREATE_USER_SESSION, LOGIN_USER, ERROR_USER, REGISTER_USER, LOGIN_USER_FAILURE
}